/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package notiontodoist;

import static org.junit.Assert.assertNotNull;

import org.junit.Test;

public class AppTest {
  @Test
  public void appHasAGreeting() {
    assertNotNull("app should have a greeting", "hello");
  }
}
